coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 80
        threshold: 5
        patch:
          default:
            target: 80
            threshold: 5

ignore:
  - "**/*_test.go"
  - "**/*_mock.go"
  - "main.go"

comment:
  layout: "header, diff, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  deletions: false

codecov:
  require_ci_to_pass: true
